In [3]:
import numpy as np

np.__version__

'1.19.5'

In [4]:
# create array from Python lists

np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [5]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [6]:
# explicitly set the data type

np.array([1, 2, 3, 4], dtype="float32")

array([1., 2., 3., 4.], dtype=float32)

In [8]:
# nested lists result in multi-dimentional arrays
# inner lists are treated as rows of the resulting 2D array

np.array([[2, 3, 4], [4, 5, 6], [6, 7, 8]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

# CREATING ARRAYS FROM SCRATCH

In [9]:
# Create a length-10 integer array filled with zeros

np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
# Create a 3x5 floating-point array filled with ones (3 rows, 5 columns)

np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
# Create a 3x5 array filled with 3.14

np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [13]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# similar to range() function

np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
# Create an array of five values evenly spaced between 0 and 1

np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [15]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1

np.random.random((3, 3))

array([[0.92242865, 0.63769099, 0.47107398],
       [0.33039305, 0.25200021, 0.94225886],
       [0.99490269, 0.89624041, 0.00815448]])

In [16]:
# Create a 3x3 array of normally distributed
# random values with mean 0 and standard deviation 1

np.random.normal(0, 1, (3, 3))

array([[ 0.10633578,  1.65212149,  0.6341541 ],
       [-1.22838639,  0.46893731,  1.43232122],
       [-1.79227049, -1.17662004, -0.04314279]])

In [17]:
# Create a 3x3 array of random integers in the interval [0, 10)

np.random.randint(0, 10, (3, 3))

array([[1, 1, 0],
       [4, 7, 5],
       [5, 1, 2]])

In [18]:
# Create a 3x3 identity matrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location

np.empty(3)

array([1., 1., 1.])

# THE BASICS OF NUMPY ARRAYS

## ARRAY ATTRIBUTES

In [20]:
import numpy as np
np.random.seed(0)

x1 = np.random.randint(10, size=6) # 1D array
x2 = np.random.randint(10, size=(3, 4)) # 2D array
x3 = np.random.randint(10, size=(3, 4, 5)) # 3D array

In [21]:
print("x3 ndim: ", x3.ndim) # number of dimensions
print("x3 shape: ", x3.shape) # size of each dimension
print("x3 size: ", x3.size) # the total size of the array

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60


In [22]:
print("x3 dtype: ", x3.dtype) # data type of the array

x3 dtype:  int64


In [23]:
print("itemsize: ", x3.itemsize, " bytes") # size (in bytes) of each array element
print("nbytes: ", x3.nbytes, " bytes") # total size (in bytes) of the array

itemsize:  8  bytes
nbytes:  480  bytes


## ARRAY INDEXING

In [25]:
x1

array([5, 0, 3, 3, 7, 9])

In [26]:
x1[-1]

9

In [27]:
x1[3]

3

In [28]:
x1[::-1]

array([9, 7, 3, 3, 0, 5])

In [29]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [30]:
x2[0, 1]

5

In [31]:
x2[-1, -1]

7

In [32]:
x2[-1, -1] = 65
x2

array([[ 3,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7, 65]])

In [33]:
x1[1] = "a"

ValueError: invalid literal for int() with base 10: 'a'

In [34]:
x1[1] = 5.6
x1

array([5, 5, 3, 3, 7, 9])

In [43]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
x[:6]

array([0, 1, 2, 3, 4, 5])

In [40]:
x[6:]

array([6, 7, 8, 9])

In [41]:
x[4:7] # middle sub-array

array([4, 5, 6])

In [42]:
x[::2] # every other element

array([0, 2, 4, 6, 8])

In [44]:
x[1::2] # every other element, starting at index 1

array([1, 3, 5, 7, 9])

In [45]:
x[::-1] # all elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [46]:
x[5::-2] # reversed every other element from index 5

array([5, 3, 1])

### MULTIDIMENSIONAL SUBARRAYS

In [47]:
x2

array([[ 3,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7, 65]])

In [48]:
x2[:2, :3] # two rows, three columns

array([[3, 5, 2],
       [7, 6, 8]])

In [49]:
x2[:, ::2] # all rows, every other column

array([[3, 2],
       [7, 8],
       [1, 7]])

In [50]:
x2[::-1, ::-1] # reverse

array([[65,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5,  3]])

In [51]:
print(x2[:, 0]) # first column of x2

[3 7 1]


In [52]:
print(x2[0, :]) # first row of x2

# can also be written as x2[0] (only in the case of rows)

[3 5 2 4]


### SUBARRAYS AND NO-COPY VIEWS

Array slices return *views* rather than *copies* of the array data.

In [53]:
print(x2)

[[ 3  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7 65]]


In [54]:
x2_sub = x2[:2, :2]

In [55]:
print(x2_sub)

[[3 5]
 [7 6]]


In [56]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [57]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7 65]]


### CREATING COPIES OF ARRAYS

In [58]:
x2_sub_copy = x2[:2, :2].copy()

In [59]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)
print(x2)

[[42  5]
 [ 7  6]]
[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7 65]]


## RESHAPING OF ARRAYS

In [63]:
# size of initial array must match the size of the reshaped array
# reshape will use no-copy view of the initial arrays
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [64]:
# conversion of a 1D array into a 2D row or column matrix
# using reshape or newaxis keyword inside slice operation

x = np.array([1, 2, 3])

# row vector via shape
x.reshape((1, 3))

array([[1, 2, 3]])

In [65]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [66]:
x

array([1, 2, 3])

In [67]:
# column vector via reshape

x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [68]:
# column vector via newaxis

x[:, np.newaxis]

array([[1],
       [2],
       [3]])

## ARRAY CONCATENATION AND SPLITTING

### CONCATENATION OF ARRAYS

Primarily accomplished using the routines np.concatenate, np.vstack, np.hstack

np.concatenate takes a tuple or list of arrays as its first argument

In [69]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [70]:
z = [99, 999, 99]
print(np.concatenate([x, y, z]))

[  1   2   3   3   2   1  99 999  99]


In [71]:
grid = np.array([[1, 2, 3], [4, 5, 6]])

In [72]:
# concatenate along first axis (rows)
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [73]:
# concatenate along second axis (columns) (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

For arrays with mixed dimensions, np.vstack (vertical) or np.hstack (horizontal). 
np.dstack is for along the third axis

In [74]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7], [6, 5, 4]])

# vertically stack the arrays (rows)
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [75]:
# horizontally stacj the arrays (columns)

y = np.array([[99], [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

### SPLITTING OF THE ARRAYS

np.split, np.hsplit, np.vsplit. For each of these, we can pass a list of indices giving the split points

In [76]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


N split-points lead to N+1 subarrays

In [77]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [78]:
# split by rows
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [79]:
# split by columns
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


# UNIVERSAL FUNCTIONS

## THE SLOWNESS OF LOOPS